local mark = require('harpoon.mark')
local ui = require('harpoon.ui')

vim.keymap.set('n', '<leader>s', mark.add_file)
vim.keymap.set('n', '<Esc>', ui.toggle_quick_menu)

-- vim.keymap.set('n', '&', function() ui.nav_file(1) end)
-- vim.keymap.set('n', '*', function() ui.nav_file(2) end)
-- vim.keymap.set('n', '(', function() ui.nav_file(3) end)
-- vim.keymap.set('n', ')', function() ui.nav_file(4) end)

vim.keymap.set('n', '<M-1>', function() ui.nav_file(1) end)
vim.keymap.set('n', '<M-2>', function() ui.nav_file(2) end)
vim.keymap.set('n', '<M-3>', function() ui.nav_file(3) end)
vim.keymap.set('n', '<M-q>', function() ui.nav_file(4) end)
vim.keymap.set('n', '<M-w>', function() ui.nav_file(5) end)
vim.keymap.set('n', '<M-e>', function() ui.nav_file(6) end)
vim.keymap.set('n', '<M-a>', function() ui.nav_file(7) end)
vim.keymap.set('n', '<M-s>', function() ui.nav_file(8) end)
vim.keymap.set('n', '<M-d>', function() ui.nav_file(9) end)
vim.keymap.set('n', '<M-z>', function() ui.nav_file(10) end)
vim.keymap.set('n', '<M-x>', function() ui.nav_file(11) end)
vim.keymap.set('n', '<M-c>', function() ui.nav_file(12) end)
